[logging]
log_level = "Trace"
json = false

[web.server]
host = "0.0.0.0"
port = 8080

[web.auth]
password_salt = "P3Z9Pya4ixZg73HH"
activation_salt = "FNi7RleyOlsjWTLi"
stretch_cost = 13
jwt_secret_key_path = "/usr/src/app/private-key.pem"
jwt_public_key_path = "/usr/src/app/public-key.pem"

[web.auth.keycloak]
id = "koudaisai-portal"
secret = "/auth/v1/admin/redirect"
issuer = "http://172.20.19.104:8080/realms/master"

[web.static_files]
web_path = "/var/www/html/web"
admin_path = "/var/www/html/admin"

[db]
address = "postgres://user:user@db/koudaisai-portal"