services:
  keycloak:
    depends_on:
      - db
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - "8080:8080"
      - "8443:8443"
    command: "start-dev"
    volumes:
      - keycloak-data:/opt/keycloak/data
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://db/koudaisai-portal"
      KC_DB_USERNAME: "user"
      KC_DB_PASSWORD: "user"
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'user'
      POSTGRES_DB: 'koudaisai-portal'

volumes:
  db-store:
  keycloak-data: