[package]
name = "koudaisai-portal-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
sea-orm = "1.1.4"
pkg-version = "1.0.0"
confy = "0.6.1"
serde = { version = "1.0.217", features = ["derive"] }
tracing = "0.1.41"
tracing-core = "0.1.33"
tracing-subscriber = "0.3.19"