openapi: 3.0.3
info:
  title: 工大祭API
  description: 工大祭のapiです。
  version: '1'
tags:
  - name: auth
    description: 工大祭アカウント 認証・認可・パスワード関連
  - name: exhibitions
    description: 参加団体関連
  - name: forms
    description: フォーム関連
  - name: form_responses
    description: フォームの回答関連
paths:
  /auth/v1/activate:
    $ref: paths/auth_v1_activate.yml
  /auth/v1/login:
    $ref: paths/auth_v1_login.yml
  /auth/v1/refresh:
    $ref: paths/auth_v1_refresh.yml
  /auth/v1/reset:
    $ref: paths/auth_v1_reset.yml
  /api/v1/exhibitions:
    $ref: paths/api_v1_exhibitions.yml
  /api/v1/exhibitions/{id}:
    $ref: paths/api_v1_exhibitions_{id}.yml
  /api/v1/forms:
    $ref: paths/api_v1_forms.yml
  /api/v1/forms/{form_id}:
    $ref: paths/api_v1_forms_{form_id}.yml
  /api/v1/forms/{form_id}/responses:
    $ref: paths/api_v1_forms_{form_id}_responses.yml
  /api/v1/forms/{form_id}/responses/{response_id}:
    $ref: paths/api_v1_forms_{form_id}_responses_{response_id}.yml
